using System.ComponentModel.DataAnnotations;

namespace CurePlease.Xi
{
    public enum SpellId
    {
        [Display(Name = "Cure")] Cure = 1,
        [Display(Name = "Cure II")] Cure2 = 2,
        [Display(Name = "Cure III")] Cure3 = 3,
        [Display(Name = "Cure IV")] Cure4 = 4,
        [Display(Name = "Cure V")] Cure5 = 5,
        [Display(Name = "Cure VI")] Cure6 = 6,
        [Display(Name = "Curaga")] Curaga = 7,
        [Display(Name = "Curaga II")] Curaga2 = 8,
        [Display(Name = "Curaga III")] Curaga3 = 9,
        [Display(Name = "Curaga IV")] Curaga4 = 10,
        [Display(Name = "Curaga V")] Curaga5 = 11,
        [Display(Name = "Raise")] Raise = 12,
        [Display(Name = "Raise II")] Raise2 = 13,
        [Display(Name = "Poisona")] Poisona = 14,
        [Display(Name = "Paralyna")] Paralyna = 15,
        [Display(Name = "Blindna")] Blindna = 16,
        [Display(Name = "Silena")] Silena = 17,
        [Display(Name = "Stona")] Stona = 18,
        [Display(Name = "Viruna")] Viruna = 19,
        [Display(Name = "Cursna")] Cursna = 20,
        [Display(Name = "Holy")] Holy = 21,
        [Display(Name = "Holy II")] Holy2 = 22,
        [Display(Name = "Dia")] Dia = 23,
        [Display(Name = "Dia II")] Dia2 = 24,
        [Display(Name = "Dia III")] Dia3 = 25,
        [Display(Name = "Dia IV")] Dia4 = 26,
        [Display(Name = "Dia V")] Dia5 = 27,
        [Display(Name = "Banish")] Banish = 28,
        [Display(Name = "Banish II")] Banish2 = 29,
        [Display(Name = "Banish III")] Banish3 = 30,
        [Display(Name = "Banish IV")] Banish4 = 31,
        [Display(Name = "Banish V")] Banish5 = 32,
        [Display(Name = "Diaga")] Diaga = 33,
        [Display(Name = "Diaga II")] Diaga2 = 34,
        [Display(Name = "Diaga III")] Diaga3 = 35,
        [Display(Name = "Diaga IV")] Diaga4 = 36,
        [Display(Name = "Diaga V")] Diaga5 = 37,
        [Display(Name = "Banishga")] Banishga = 38,
        [Display(Name = "Banishga II")] Banishga2 = 39,
        [Display(Name = "Banishga III")] Banishga3 = 40,
        [Display(Name = "Banishga IV")] Banishga4 = 41,
        [Display(Name = "Banishga V")] Banishga5 = 42,
        [Display(Name = "Protect")] Protect = 43,
        [Display(Name = "Protect II")] Protect2 = 44,
        [Display(Name = "Protect III")] Protect3 = 45,
        [Display(Name = "Protect IV")] Protect4 = 46,
        [Display(Name = "Protect V")] Protect5 = 47,
        [Display(Name = "Shell")] Shell = 48,
        [Display(Name = "Shell II")] Shell2 = 49,
        [Display(Name = "Shell III")] Shell3 = 50,
        [Display(Name = "Shell IV")] Shell4 = 51,
        [Display(Name = "Shell V")] Shell5 = 52,
        [Display(Name = "Blink")] Blink = 53,
        [Display(Name = "Stoneskin")] Stoneskin = 54,
        [Display(Name = "Aquaveil")] Aquaveil = 55,
        [Display(Name = "Slow")] Slow = 56,
        [Display(Name = "Haste")] Haste = 57,
        [Display(Name = "Paralyze")] Paralyze = 58,
        [Display(Name = "Silence")] Silence = 59,
        [Display(Name = "Barfire")] Barfire = 60,
        [Display(Name = "Barblizzard")] Barblizzard = 61,
        [Display(Name = "Baraero")] Baraero = 62,
        [Display(Name = "Barstone")] Barstone = 63,
        [Display(Name = "Barthunder")] Barthunder = 64,
        [Display(Name = "Barwater")] Barwater = 65,
        [Display(Name = "Barfira")] Barfira = 66,
        [Display(Name = "Barblizzara")] Barblizzara = 67,
        [Display(Name = "Baraera")] Baraera = 68,
        [Display(Name = "Barstonra")] Barstonra = 69,
        [Display(Name = "Barthundra")] Barthundra = 70,
        [Display(Name = "Barwatera")] Barwatera = 71,
        [Display(Name = "Barsleep")] Barsleep = 72,
        [Display(Name = "Barpoison")] Barpoison = 73,
        [Display(Name = "Barparalyze")] Barparalyze = 74,
        [Display(Name = "Barblind")] Barblind = 75,
        [Display(Name = "Barsilence")] Barsilence = 76,
        [Display(Name = "Barpetrify")] Barpetrify = 77,
        [Display(Name = "Barvirus")] Barvirus = 78,
        [Display(Name = "Slow II")] Slow2 = 79,
        [Display(Name = "Paralyze II")] Paralyze2 = 80,
        [Display(Name = "Recall-Jugner")] RecallJugner = 81,
        [Display(Name = "Recall-Pashh")] RecallPashh = 82,
        [Display(Name = "Recall-Meriph")] RecallMeriph = 83,
        [Display(Name = "Baramnesia")] Baramnesia = 84,
        [Display(Name = "Baramnesra")] Baramnesra = 85,
        [Display(Name = "Barsleepra")] Barsleepra = 86,
        [Display(Name = "Barpoisonra")] Barpoisonra = 87,
        [Display(Name = "Barparalyzra")] Barparalyzra = 88,
        [Display(Name = "Barblindra")] Barblindra = 89,
        [Display(Name = "Barsilencera")] Barsilencera = 90,
        [Display(Name = "Barpetra")] Barpetra = 91,
        [Display(Name = "Barvira")] Barvira = 92,
        [Display(Name = "Cura")] Cura = 93,
        [Display(Name = "Sacrifice")] Sacrifice = 94,
        [Display(Name = "Esuna")] Esuna = 95,
        [Display(Name = "Auspice")] Auspice = 96,
        [Display(Name = "Reprisal")] Reprisal = 97,
        [Display(Name = "Repose")] Repose = 98,
        [Display(Name = "Sandstorm")] Sandstorm = 99,
        [Display(Name = "Enfire")] Enfire = 100,
        [Display(Name = "Enblizzard")] Enblizzard = 101,
        [Display(Name = "Enaero")] Enaero = 102,
        [Display(Name = "Enstone")] Enstone = 103,
        [Display(Name = "Enthunder")] Enthunder = 104,
        [Display(Name = "Enwater")] Enwater = 105,
        [Display(Name = "Phalanx")] Phalanx = 106,
        [Display(Name = "Phalanx II")] Phalanx2 = 107,
        [Display(Name = "Regen")] Regen = 108,
        [Display(Name = "Refresh")] Refresh = 109,
        [Display(Name = "Regen II")] Regen2 = 110,
        [Display(Name = "Regen III")] Regen3 = 111,
        [Display(Name = "Flash")] Flash = 112,
        [Display(Name = "Rainstorm")] Rainstorm = 113,
        [Display(Name = "Windstorm")] Windstorm = 114,
        [Display(Name = "Firestorm")] Firestorm = 115,
        [Display(Name = "Hailstorm")] Hailstorm = 116,
        [Display(Name = "Thunderstorm")] Thunderstorm = 117,
        [Display(Name = "Voidstorm")] Voidstorm = 118,
        [Display(Name = "Aurorastorm")] Aurorastorm = 119,
        [Display(Name = "Teleport-Yhoat")] TeleportYhoat = 120,
        [Display(Name = "Teleport-Altep")] TeleportAltep = 121,
        [Display(Name = "Teleport-Holla")] TeleportHolla = 122,
        [Display(Name = "Teleport-Dem")] TeleportDem = 123,
        [Display(Name = "Teleport-Mea")] TeleportMea = 124,
        [Display(Name = "Protectra")] Protectra = 125,
        [Display(Name = "Protectra II")] Protectra2 = 126,
        [Display(Name = "Protectra III")] Protectra3 = 127,
        [Display(Name = "Protectra IV")] Protectra4 = 128,
        [Display(Name = "Protectra V")] Protectra5 = 129,
        [Display(Name = "Shellra")] Shellra = 130,
        [Display(Name = "Shellra II")] Shellra2 = 131,
        [Display(Name = "Shellra III")] Shellra3 = 132,
        [Display(Name = "Shellra IV")] Shellra4 = 133,
        [Display(Name = "Shellra V")] Shellra5 = 134,
        [Display(Name = "Reraise")] Reraise = 135,
        [Display(Name = "Invisible")] Invisible = 136,
        [Display(Name = "Sneak")] Sneak = 137,
        [Display(Name = "Deodorize")] Deodorize = 138,
        [Display(Name = "Teleport-Vahzl")] TeleportVahzl = 139,
        [Display(Name = "Raise III")] Raise3 = 140,
        [Display(Name = "Reraise II")] Reraise2 = 141,
        [Display(Name = "Reraise III")] Reraise3 = 142,
        [Display(Name = "Erase")] Erase = 143,
        [Display(Name = "Fire")] Fire = 144,
        [Display(Name = "Fire II")] Fire2 = 145,
        [Display(Name = "Fire III")] Fire3 = 146,
        [Display(Name = "Fire IV")] Fire4 = 147,
        [Display(Name = "Fire V")] Fire5 = 148,
        [Display(Name = "Blizzard")] Blizzard = 149,
        [Display(Name = "Blizzard II")] Blizzard2 = 150,
        [Display(Name = "Blizzard III")] Blizzard3 = 151,
        [Display(Name = "Blizzard IV")] Blizzard4 = 152,
        [Display(Name = "Blizzard V")] Blizzard5 = 153,
        [Display(Name = "Aero")] Aero = 154,
        [Display(Name = "Aero II")] Aero2 = 155,
        [Display(Name = "Aero III")] Aero3 = 156,
        [Display(Name = "Aero IV")] Aero4 = 157,
        [Display(Name = "Aero V")] Aero5 = 158,
        [Display(Name = "Stone")] Stone = 159,
        [Display(Name = "Stone II")] Stone2 = 160,
        [Display(Name = "Stone III")] Stone3 = 161,
        [Display(Name = "Stone IV")] Stone4 = 162,
        [Display(Name = "Stone V")] Stone5 = 163,
        [Display(Name = "Thunder")] Thunder = 164,
        [Display(Name = "Thunder II")] Thunder2 = 165,
        [Display(Name = "Thunder III")] Thunder3 = 166,
        [Display(Name = "Thunder IV")] Thunder4 = 167,
        [Display(Name = "Thunder V")] Thunder5 = 168,
        [Display(Name = "Water")] Water = 169,
        [Display(Name = "Water II")] Water2 = 170,
        [Display(Name = "Water III")] Water3 = 171,
        [Display(Name = "Water IV")] Water4 = 172,
        [Display(Name = "Water V")] Water5 = 173,
        [Display(Name = "Firaga")] Firaga = 174,
        [Display(Name = "Firaga II")] Firaga2 = 175,
        [Display(Name = "Firaga III")] Firaga3 = 176,
        [Display(Name = "Firaga IV")] Firaga4 = 177,
        [Display(Name = "Firaga V")] Firaga5 = 178,
        [Display(Name = "Blizzaga")] Blizzaga = 179,
        [Display(Name = "Blizzaga II")] Blizzaga2 = 180,
        [Display(Name = "Blizzaga III")] Blizzaga3 = 181,
        [Display(Name = "Blizzaga IV")] Blizzaga4 = 182,
        [Display(Name = "Blizzaga V")] Blizzaga5 = 183,
        [Display(Name = "Aeroga")] Aeroga = 184,
        [Display(Name = "Aeroga II")] Aeroga2 = 185,
        [Display(Name = "Aeroga III")] Aeroga3 = 186,
        [Display(Name = "Aeroga IV")] Aeroga4 = 187,
        [Display(Name = "Aeroga V")] Aeroga5 = 188,
        [Display(Name = "Stonega")] Stonega = 189,
        [Display(Name = "Stonega II")] Stonega2 = 190,
        [Display(Name = "Stonega III")] Stonega3 = 191,
        [Display(Name = "Stonega IV")] Stonega4 = 192,
        [Display(Name = "Stonega V")] Stonega5 = 193,
        [Display(Name = "Thundaga")] Thundaga = 194,
        [Display(Name = "Thundaga II")] Thundaga2 = 195,
        [Display(Name = "Thundaga III")] Thundaga3 = 196,
        [Display(Name = "Thundaga IV")] Thundaga4 = 197,
        [Display(Name = "Thundaga V")] Thundaga5 = 198,
        [Display(Name = "Waterga")] Waterga = 199,
        [Display(Name = "Waterga II")] Waterga2 = 200,
        [Display(Name = "Waterga III")] Waterga3 = 201,
        [Display(Name = "Waterga IV")] Waterga4 = 202,
        [Display(Name = "Waterga V")] Waterga5 = 203,
        [Display(Name = "Flare")] Flare = 204,
        [Display(Name = "Flare II")] Flare2 = 205,
        [Display(Name = "Freeze")] Freeze = 206,
        [Display(Name = "Freeze II")] Freeze2 = 207,
        [Display(Name = "Tornado")] Tornado = 208,
        [Display(Name = "Tornado II")] Tornado2 = 209,
        [Display(Name = "Quake")] Quake = 210,
        [Display(Name = "Quake II")] Quake2 = 211,
        [Display(Name = "Burst")] Burst = 212,
        [Display(Name = "Burst II")] Burst2 = 213,
        [Display(Name = "Flood")] Flood = 214,
        [Display(Name = "Flood II")] Flood2 = 215,
        [Display(Name = "Gravity")] Gravity = 216,
        [Display(Name = "Gravity II")] Gravity2 = 217,
        [Display(Name = "Meteor")] Meteor = 218,
        [Display(Name = "Comet")] Comet = 219,
        [Display(Name = "Poison")] Poison = 220,
        [Display(Name = "Poison II")] Poison2 = 221,
        [Display(Name = "Poison III")] Poison3 = 222,
        [Display(Name = "Poison IV")] Poison4 = 223,
        [Display(Name = "Poison V")] Poison5 = 224,
        [Display(Name = "Poisonga")] Poisonga = 225,
        [Display(Name = "Poisonga II")] Poisonga2 = 226,
        [Display(Name = "Poisonga III")] Poisonga3 = 227,
        [Display(Name = "Poisonga IV")] Poisonga4 = 228,
        [Display(Name = "Poisonga V")] Poisonga5 = 229,
        [Display(Name = "Bio")] Bio = 230,
        [Display(Name = "Bio II")] Bio2 = 231,
        [Display(Name = "Bio III")] Bio3 = 232,
        [Display(Name = "Bio IV")] Bio4 = 233,
        [Display(Name = "Bio V")] Bio5 = 234,
        [Display(Name = "Burn")] Burn = 235,
        [Display(Name = "Frost")] Frost = 236,
        [Display(Name = "Choke")] Choke = 237,
        [Display(Name = "Rasp")] Rasp = 238,
        [Display(Name = "Shock")] Shock = 239,
        [Display(Name = "Drown")] Drown = 240,
        [Display(Name = "Retrace")] Retrace = 241,
        [Display(Name = "Absorb-ACC")] AbsorbACC = 242,
        [Display(Name = "Absorb-Attri")] AbsorbAttri = 243,
        [Display(Name = "Meteor II")] Meteor2 = 244,
        [Display(Name = "Drain")] Drain = 245,
        [Display(Name = "Drain II")] Drain2 = 246,
        [Display(Name = "Aspir")] Aspir = 247,
        [Display(Name = "Aspir II")] Aspir2 = 248,
        [Display(Name = "Blaze Spikes")] BlazeSpikes = 249,
        [Display(Name = "Ice Spikes")] IceSpikes = 250,
        [Display(Name = "Shock Spikes")] ShockSpikes = 251,
        [Display(Name = "Stun")] Stun = 252,
        [Display(Name = "Sleep")] Sleep = 253,
        [Display(Name = "Blind")] Blind = 254,
        [Display(Name = "Break")] Break = 255,
        [Display(Name = "Virus")] Virus = 256,
        [Display(Name = "Curse")] Curse = 257,
        [Display(Name = "Bind")] Bind = 258,
        [Display(Name = "Sleep II")] Sleep2 = 259,
        [Display(Name = "Dispel")] Dispel = 260,
        [Display(Name = "Warp")] Warp = 261,
        [Display(Name = "Warp II")] Warp2 = 262,
        [Display(Name = "Escape")] Escape = 263,
        [Display(Name = "Tractor")] Tractor = 264,
        [Display(Name = "Tractor II")] Tractor2 = 265,
        [Display(Name = "Absorb-STR")] AbsorbSTR = 266,
        [Display(Name = "Absorb-DEX")] AbsorbDEX = 267,
        [Display(Name = "Absorb-VIT")] AbsorbVIT = 268,
        [Display(Name = "Absorb-AGI")] AbsorbAGI = 269,
        [Display(Name = "Absorb-INT")] AbsorbINT = 270,
        [Display(Name = "Absorb-MND")] AbsorbMND = 271,
        [Display(Name = "Absorb-CHR")] AbsorbCHR = 272,
        [Display(Name = "Sleepga")] Sleepga = 273,
        [Display(Name = "Sleepga II")] Sleepga2 = 274,
        [Display(Name = "Absorb-TP")] AbsorbTP = 275,
        [Display(Name = "Blind II")] Blind2 = 276,
        [Display(Name = "Dread Spikes")] DreadSpikes = 277,
        [Display(Name = "Geohelix")] Geohelix = 278,
        [Display(Name = "Hydrohelix")] Hydrohelix = 279,
        [Display(Name = "Anemohelix")] Anemohelix = 280,
        [Display(Name = "Pyrohelix")] Pyrohelix = 281,
        [Display(Name = "Cryohelix")] Cryohelix = 282,
        [Display(Name = "Ionohelix")] Ionohelix = 283,
        [Display(Name = "Noctohelix")] Noctohelix = 284,
        [Display(Name = "Luminohelix")] Luminohelix = 285,
        [Display(Name = "Addle")] Addle = 286,
        [Display(Name = "Klimaform")] Klimaform = 287,
        [Display(Name = "Fire Spirit")] FireSpirit = 288,
        [Display(Name = "Ice Spirit")] IceSpirit = 289,
        [Display(Name = "Air Spirit")] AirSpirit = 290,
        [Display(Name = "Earth Spirit")] EarthSpirit = 291,
        [Display(Name = "Thunder Spirit")] ThunderSpirit = 292,
        [Display(Name = "Water Spirit")] WaterSpirit = 293,
        [Display(Name = "Light Spirit")] LightSpirit = 294,
        [Display(Name = "Dark Spirit")] DarkSpirit = 295,
        [Display(Name = "Carbuncle")] Carbuncle = 296,
        [Display(Name = "Fenrir")] Fenrir = 297,
        [Display(Name = "Ifrit")] Ifrit = 298,
        [Display(Name = "Titan")] Titan = 299,
        [Display(Name = "Leviathan")] Leviathan = 300,
        [Display(Name = "Garuda")] Garuda = 301,
        [Display(Name = "Shiva")] Shiva = 302,
        [Display(Name = "Ramuh")] Ramuh = 303,
        [Display(Name = "Diabolos")] Diabolos = 304,
        [Display(Name = "Odin")] Odin = 305,
        [Display(Name = "Alexander")] Alexander = 306,
        [Display(Name = "Cait Sith")] CaitSith = 307,
        [Display(Name = "Animus Augeo")] AnimusAugeo = 308,
        [Display(Name = "Animus Minuo")] AnimusMinuo = 309,
        [Display(Name = "Enlight")] Enlight = 310,
        [Display(Name = "Endark")] Endark = 311,
        [Display(Name = "Enfire II")] Enfire2 = 312,
        [Display(Name = "Enblizzard II")] Enblizzard2 = 313,
        [Display(Name = "Enaero II")] Enaero2 = 314,
        [Display(Name = "Enstone II")] Enstone2 = 315,
        [Display(Name = "Enthunder II")] Enthunder2 = 316,
        [Display(Name = "Enwater II")] Enwater2 = 317,
        [Display(Name = "Monomi: Ichi")] MonomiIchi = 318,
        [Display(Name = "Aisha: Ichi")] AishaIchi = 319,
        [Display(Name = "Katon: Ichi")] KatonIchi = 320,
        [Display(Name = "Katon: Ni")] KatonNi = 321,
        [Display(Name = "Katon: San")] KatonSan = 322,
        [Display(Name = "Hyoton: Ichi")] HyotonIchi = 323,
        [Display(Name = "Hyoton: Ni")] HyotonNi = 324,
        [Display(Name = "Hyoton: San")] HyotonSan = 325,
        [Display(Name = "Huton: Ichi")] HutonIchi = 326,
        [Display(Name = "Huton: Ni")] HutonNi = 327,
        [Display(Name = "Huton: San")] HutonSan = 328,
        [Display(Name = "Doton: Ichi")] DotonIchi = 329,
        [Display(Name = "Doton: Ni")] DotonNi = 330,
        [Display(Name = "Doton: San")] DotonSan = 331,
        [Display(Name = "Raiton: Ichi")] RaitonIchi = 332,
        [Display(Name = "Raiton: Ni")] RaitonNi = 333,
        [Display(Name = "Raiton: San")] RaitonSan = 334,
        [Display(Name = "Suiton: Ichi")] SuitonIchi = 335,
        [Display(Name = "Suiton: Ni")] SuitonNi = 336,
        [Display(Name = "Suiton: San")] SuitonSan = 337,
        [Display(Name = "Utsusemi: Ichi")] UtsusemiIchi = 338,
        [Display(Name = "Utsusemi: Ni")] UtsusemiNi = 339,
        [Display(Name = "Utsusemi: San")] UtsusemiSan = 340,
        [Display(Name = "Jubaku: Ichi")] JubakuIchi = 341,
        [Display(Name = "Jubaku: Ni")] JubakuNi = 342,
        [Display(Name = "Jubaku: San")] JubakuSan = 343,
        [Display(Name = "Hojo: Ichi")] HojoIchi = 344,
        [Display(Name = "Hojo: Ni")] HojoNi = 345,
        [Display(Name = "Hojo: San")] HojoSan = 346,
        [Display(Name = "Kurayami: Ichi")] KurayamiIchi = 347,
        [Display(Name = "Kurayami: Ni")] KurayamiNi = 348,
        [Display(Name = "Kurayami: San")] KurayamiSan = 349,
        [Display(Name = "Dokumori: Ichi")] DokumoriIchi = 350,
        [Display(Name = "Dokumori: Ni")] DokumoriNi = 351,
        [Display(Name = "Dokumori: San")] DokumoriSan = 352,
        [Display(Name = "Tonko: Ichi")] TonkoIchi = 353,
        [Display(Name = "Tonko: Ni")] TonkoNi = 354,
        [Display(Name = "Siren")] Siren = 355,
        [Display(Name = "Paralyga")] Paralyga = 356,
        [Display(Name = "Slowga")] Slowga = 357,
        [Display(Name = "Hastega")] Hastega = 358,
        [Display(Name = "Silencega")] Silencega = 359,
        [Display(Name = "Dispelga")] Dispelga = 360,
        [Display(Name = "Blindga")] Blindga = 361,
        [Display(Name = "Bindga")] Bindga = 362,
        [Display(Name = "Breakga")] Breakga = 365,
        [Display(Name = "Graviga")] Graviga = 366,
        [Display(Name = "Death")] Death = 367,
        [Display(Name = "Foe Requiem")] FoeRequiem = 368,
        [Display(Name = "Foe Requiem II")] FoeRequiem2 = 369,
        [Display(Name = "Foe Requiem III")] FoeRequiem3 = 370,
        [Display(Name = "Foe Requiem IV")] FoeRequiem4 = 371,
        [Display(Name = "Foe Requiem V")] FoeRequiem5 = 372,
        [Display(Name = "Foe Requiem VI")] FoeRequiem6 = 373,
        [Display(Name = "Foe Requiem VII")] FoeRequiem7 = 374,
        [Display(Name = "Foe Requiem VIII")] FoeRequiem8 = 375,
        [Display(Name = "Horde Lullaby")] HordeLullaby = 376,
        [Display(Name = "Horde Lullaby II")] HordeLullaby2 = 377,
        [Display(Name = "Army's Paeon")] ArmysPaeon = 378,
        [Display(Name = "Army's Paeon II")] ArmysPaeon2 = 379,
        [Display(Name = "Army's Paeon III")] ArmysPaeon3 = 380,
        [Display(Name = "Army's Paeon IV")] ArmysPaeon4 = 381,
        [Display(Name = "Army's Paeon V")] ArmysPaeon5 = 382,
        [Display(Name = "Army's Paeon VI")] ArmysPaeon6 = 383,
        [Display(Name = "Army's Paeon VII")] ArmysPaeon7 = 384,
        [Display(Name = "Army's Paeon VIII")] ArmysPaeon8 = 385,
        [Display(Name = "Mage's Ballad")] MagesBallad = 386,
        [Display(Name = "Mage's Ballad II")] MagesBallad2 = 387,
        [Display(Name = "Mage's Ballad III")] MagesBallad3 = 388,
        [Display(Name = "Knight's Minne")] KnightsMinne = 389,
        [Display(Name = "Knight's Minne II")] KnightsMinne2 = 390,
        [Display(Name = "Knight's Minne III")] KnightsMinne3 = 391,
        [Display(Name = "Knight's Minne IV")] KnightsMinne4 = 392,
        [Display(Name = "Knight's Minne V")] KnightsMinne5 = 393,
        [Display(Name = "Valor Minuet")] ValorMinuet = 394,
        [Display(Name = "Valor Minuet II")] ValorMinuet2 = 395,
        [Display(Name = "Valor Minuet III")] ValorMinuet3 = 396,
        [Display(Name = "Valor Minuet IV")] ValorMinuet4 = 397,
        [Display(Name = "Valor Minuet V")] ValorMinuet5 = 398,
        [Display(Name = "Sword Madrigal")] SwordMadrigal = 399,
        [Display(Name = "Blade Madrigal")] BladeMadrigal = 400,
        [Display(Name = "Hunter's Prelude")] HuntersPrelude = 401,
        [Display(Name = "Archer's Prelude")] ArchersPrelude = 402,
        [Display(Name = "Sheepfoe Mambo")] SheepfoeMambo = 403,
        [Display(Name = "Dragonfoe Mambo")] DragonfoeMambo = 404,
        [Display(Name = "Fowl Aubade")] FowlAubade = 405,
        [Display(Name = "Herb Pastoral")] HerbPastoral = 406,
        [Display(Name = "Chocobo Hum")] ChocoboHum = 407,
        [Display(Name = "Shining Fantasia")] ShiningFantasia = 408,
        [Display(Name = "Scop's Operetta")] ScopsOperetta = 409,
        [Display(Name = "Puppet's Operetta")] PuppetsOperetta = 410,
        [Display(Name = "Jester's Operetta")] JestersOperetta = 411,
        [Display(Name = "Gold Capriccio")] GoldCapriccio = 412,
        [Display(Name = "Devotee Serenade")] DevoteeSerenade = 413,
        [Display(Name = "Warding Round")] WardingRound = 414,
        [Display(Name = "Goblin Gavotte")] GoblinGavotte = 415,
        [Display(Name = "Cactuar Fugue")] CactuarFugue = 416,
        [Display(Name = "Honor March")] HonorMarch = 417,
        [Display(Name = "Protected Aria")] ProtectedAria = 418,
        [Display(Name = "Advancing March")] AdvancingMarch = 419,
        [Display(Name = "Victory March")] VictoryMarch = 420,
        [Display(Name = "Battlefield Elegy")] BattlefieldElegy = 421,
        [Display(Name = "Carnage Elegy")] CarnageElegy = 422,
        [Display(Name = "Massacre Elegy")] MassacreElegy = 423,
        [Display(Name = "Sinewy Etude")] SinewyEtude = 424,
        [Display(Name = "Dextrous Etude")] DextrousEtude = 425,
        [Display(Name = "Vivacious Etude")] VivaciousEtude = 426,
        [Display(Name = "Quick Etude")] QuickEtude = 427,
        [Display(Name = "Learned Etude")] LearnedEtude = 428,
        [Display(Name = "Spirited Etude")] SpiritedEtude = 429,
        [Display(Name = "Enchanting Etude")] EnchantingEtude = 430,
        [Display(Name = "Herculean Etude")] HerculeanEtude = 431,
        [Display(Name = "Uncanny Etude")] UncannyEtude = 432,
        [Display(Name = "Vital Etude")] VitalEtude = 433,
        [Display(Name = "Swift Etude")] SwiftEtude = 434,
        [Display(Name = "Sage Etude")] SageEtude = 435,
        [Display(Name = "Logical Etude")] LogicalEtude = 436,
        [Display(Name = "Bewitching Etude")] BewitchingEtude = 437,
        [Display(Name = "Fire Carol")] FireCarol = 438,
        [Display(Name = "Ice Carol")] IceCarol = 439,
        [Display(Name = "Wind Carol")] WindCarol = 440,
        [Display(Name = "Earth Carol")] EarthCarol = 441,
        [Display(Name = "Lightning Carol")] LightningCarol = 442,
        [Display(Name = "Water Carol")] WaterCarol = 443,
        [Display(Name = "Light Carol")] LightCarol = 444,
        [Display(Name = "Dark Carol")] DarkCarol = 445,
        [Display(Name = "Fire Carol II")] FireCarol2 = 446,
        [Display(Name = "Ice Carol II")] IceCarol2 = 447,
        [Display(Name = "Wind Carol II")] WindCarol2 = 448,
        [Display(Name = "Earth Carol II")] EarthCarol2 = 449,
        [Display(Name = "Lightning Carol II")] LightningCarol2 = 450,
        [Display(Name = "Water Carol II")] WaterCarol2 = 451,
        [Display(Name = "Light Carol II")] LightCarol2 = 452,
        [Display(Name = "Dark Carol II")] DarkCarol2 = 453,
        [Display(Name = "Fire Threnody")] FireThrenody = 454,
        [Display(Name = "Ice Threnody")] IceThrenody = 455,
        [Display(Name = "Wind Threnody")] WindThrenody = 456,
        [Display(Name = "Earth Threnody")] EarthThrenody = 457,
        [Display(Name = "Ltng. Threnody")] LtngThrenody = 458,
        [Display(Name = "Water Threnody")] WaterThrenody = 459,
        [Display(Name = "Light Threnody")] LightThrenody = 460,
        [Display(Name = "Dark Threnody")] DarkThrenody = 461,
        [Display(Name = "Magic Finale")] MagicFinale = 462,
        [Display(Name = "Foe Lullaby")] FoeLullaby = 463,
        [Display(Name = "Goddess's Hymnus")] GoddesssHymnus = 464,
        [Display(Name = "Chocobo Mazurka")] ChocoboMazurka = 465,
        [Display(Name = "Maiden's Virelai")] MaidensVirelai = 466,
        [Display(Name = "Raptor Mazurka")] RaptorMazurka = 467,
        [Display(Name = "Foe Sirvente")] FoeSirvente = 468,
        [Display(Name = "Adventurer's Dirge")] AdventurersDirge = 469,
        [Display(Name = "Sentinel's Scherzo")] SentinelsScherzo = 470,
        [Display(Name = "Foe Lullaby II")] FoeLullaby2 = 471,
        [Display(Name = "Pining Nocturne")] PiningNocturne = 472,
        [Display(Name = "Refresh II")] Refresh2 = 473,
        [Display(Name = "Cura II")] Cura2 = 474,
        [Display(Name = "Cura III")] Cura3 = 475,
        [Display(Name = "Crusade")] Crusade = 476,
        [Display(Name = "Regen IV")] Regen4 = 477,
        [Display(Name = "Embrava")] Embrava = 478,
        [Display(Name = "Boost-STR")] BoostSTR = 479,
        [Display(Name = "Boost-DEX")] BoostDEX = 480,
        [Display(Name = "Boost-VIT")] BoostVIT = 481,
        [Display(Name = "Boost-AGI")] BoostAGI = 482,
        [Display(Name = "Boost-INT")] BoostINT = 483,
        [Display(Name = "Boost-MND")] BoostMND = 484,
        [Display(Name = "Boost-CHR")] BoostCHR = 485,
        [Display(Name = "Gain-STR")] GainSTR = 486,
        [Display(Name = "Gain-DEX")] GainDEX = 487,
        [Display(Name = "Gain-VIT")] GainVIT = 488,
        [Display(Name = "Gain-AGI")] GainAGI = 489,
        [Display(Name = "Gain-INT")] GainINT = 490,
        [Display(Name = "Gain-MND")] GainMND = 491,
        [Display(Name = "Gain-CHR")] GainCHR = 492,
        [Display(Name = "Temper")] Temper = 493,
        [Display(Name = "Arise")] Arise = 494,
        [Display(Name = "Adloquium")] Adloquium = 495,
        [Display(Name = "Firaja")] Firaja = 496,
        [Display(Name = "Blizzaja")] Blizzaja = 497,
        [Display(Name = "Aeroja")] Aeroja = 498,
        [Display(Name = "Stoneja")] Stoneja = 499,
        [Display(Name = "Thundaja")] Thundaja = 500,
        [Display(Name = "Waterja")] Waterja = 501,
        [Display(Name = "Kaustra")] Kaustra = 502,
        [Display(Name = "Impact")] Impact = 503,
        [Display(Name = "Regen V")] Regen5 = 504,
        [Display(Name = "Gekka: Ichi")] GekkaIchi = 505,
        [Display(Name = "Yain: Ichi")] YainIchi = 506,
        [Display(Name = "Myoshu: Ichi")] MyoshuIchi = 507,
        [Display(Name = "Yurin: Ichi")] YurinIchi = 508,
        [Display(Name = "Kakka: Ichi")] KakkaIchi = 509,
        [Display(Name = "Migawari: Ichi")] MigawariIchi = 510,
        [Display(Name = "Haste II")] Haste2 = 511,
        [Display(Name = "Venom Shell")] VenomShell = 513,
        [Display(Name = "Maelstrom")] Maelstrom = 515,
        [Display(Name = "Metallic Body")] MetallicBody = 517,
        [Display(Name = "Screwdriver")] Screwdriver = 519,
        [Display(Name = "MP Drainkiss")] MPDrainkiss = 521,
        [Display(Name = "Death Ray")] DeathRay = 522,
        [Display(Name = "Sandspin")] Sandspin = 524,
        [Display(Name = "Smite of Rage")] SmiteOfRage = 527,
        [Display(Name = "Bludgeon")] Bludgeon = 529,
        [Display(Name = "Refueling")] Refueling = 530,
        [Display(Name = "Ice Break")] IceBreak = 531,
        [Display(Name = "Blitzstrahl")] Blitzstrahl = 532,
        [Display(Name = "Self-Destruct")] SelfDestruct = 533,
        [Display(Name = "Mysterious Light")] MysteriousLight = 534,
        [Display(Name = "Cold Wave")] ColdWave = 535,
        [Display(Name = "Poison Breath")] PoisonBreath = 536,
        [Display(Name = "Stinking Gas")] StinkingGas = 537,
        [Display(Name = "Memento Mori")] MementoMori = 538,
        [Display(Name = "Terror Touch")] TerrorTouch = 539,
        [Display(Name = "Spinal Cleave")] SpinalCleave = 540,
        [Display(Name = "Blood Saber")] BloodSaber = 541,
        [Display(Name = "Digest")] Digest = 542,
        [Display(Name = "Mandibular Bite")] MandibularBite = 543,
        [Display(Name = "Cursed Sphere")] CursedSphere = 544,
        [Display(Name = "Sickle Slash")] SickleSlash = 545,
        [Display(Name = "Cocoon")] Cocoon = 547,
        [Display(Name = "Filamented Hold")] FilamentedHold = 548,
        [Display(Name = "Pollen")] Pollen = 549,
        [Display(Name = "Power Attack")] PowerAttack = 551,
        [Display(Name = "Death Scissors")] DeathScissors = 554,
        [Display(Name = "Magnetite Cloud")] MagnetiteCloud = 555,
        [Display(Name = "Eyes On Me")] EyesOnMe = 557,
        [Display(Name = "Frenetic Rip")] FreneticRip = 560,
        [Display(Name = "Frightful Roar")] FrightfulRoar = 561,
        [Display(Name = "Hecatomb Wave")] HecatombWave = 563,
        [Display(Name = "Body Slam")] BodySlam = 564,
        [Display(Name = "Radiant Breath")] RadiantBreath = 565,
        [Display(Name = "Helldive")] Helldive = 567,
        [Display(Name = "Jet Stream")] JetStream = 569,
        [Display(Name = "Blood Drain")] BloodDrain = 570,
        [Display(Name = "Sound Blast")] SoundBlast = 572,
        [Display(Name = "Feather Tickle")] FeatherTickle = 573,
        [Display(Name = "Feather Barrier")] FeatherBarrier = 574,
        [Display(Name = "Jettatura")] Jettatura = 575,
        [Display(Name = "Yawn")] Yawn = 576,
        [Display(Name = "Foot Kick")] FootKick = 577,
        [Display(Name = "Wild Carrot")] WildCarrot = 578,
        [Display(Name = "Voracious Trunk")] VoraciousTrunk = 579,
        [Display(Name = "Healing Breeze")] HealingBreeze = 581,
        [Display(Name = "Chaotic Eye")] ChaoticEye = 582,
        [Display(Name = "Sheep Song")] SheepSong = 584,
        [Display(Name = "Ram Charge")] RamCharge = 585,
        [Display(Name = "Claw Cyclone")] ClawCyclone = 587,
        [Display(Name = "Lowing")] Lowing = 588,
        [Display(Name = "Dimensional Death")] DimensionalDeath = 589,
        [Display(Name = "Heat Breath")] HeatBreath = 591,
        [Display(Name = "Blank Gaze")] BlankGaze = 592,
        [Display(Name = "Magic Fruit")] MagicFruit = 593,
        [Display(Name = "Uppercut")] Uppercut = 594,
        [Display(Name = "1000 Needles")] ThousandNeedles = 595,
        [Display(Name = "Pinecone Bomb")] PineconeBomb = 596,
        [Display(Name = "Sprout Smack")] SproutSmack = 597,
        [Display(Name = "Soporific")] Soporific = 598,
        [Display(Name = "Queasyshroom")] Queasyshroom = 599,
        [Display(Name = "Wild Oats")] WildOats = 603,
        [Display(Name = "Bad Breath")] BadBreath = 604,
        [Display(Name = "Geist Wall")] GeistWall = 605,
        [Display(Name = "Awful Eye")] AwfulEye = 606,
        [Display(Name = "Frost Breath")] FrostBreath = 608,
        [Display(Name = "Infrasonics")] Infrasonics = 610,
        [Display(Name = "Disseverment")] Disseverment = 611,
        [Display(Name = "Actinic Burst")] ActinicBurst = 612,
        [Display(Name = "Reactor Cool")] ReactorCool = 613,
        [Display(Name = "Saline Coat")] SalineCoat = 614,
        [Display(Name = "Plasma Charge")] PlasmaCharge = 615,
        [Display(Name = "Temporal Shift")] TemporalShift = 616,
        [Display(Name = "Vertical Cleave")] VerticalCleave = 617,
        [Display(Name = "Blastbomb")] Blastbomb = 618,
        [Display(Name = "Battle Dance")] BattleDance = 620,
        [Display(Name = "Sandspray")] Sandspray = 621,
        [Display(Name = "Grand Slam")] GrandSlam = 622,
        [Display(Name = "Head Butt")] HeadButt = 623,
        [Display(Name = "Bomb Toss")] BombToss = 626,
        [Display(Name = "Frypan")] Frypan = 628,
        [Display(Name = "Flying Hip Press")] FlyingHipPress = 629,
        [Display(Name = "Hydro Shot")] HydroShot = 631,
        [Display(Name = "Diamondhide")] Diamondhide = 632,
        [Display(Name = "Enervation")] Enervation = 633,
        [Display(Name = "Light of Penance")] LightOfPenance = 634,
        [Display(Name = "Warm-Up")] WarmUp = 636,
        [Display(Name = "Firespit")] Firespit = 637,
        [Display(Name = "Feather Storm")] FeatherStorm = 638,
        [Display(Name = "Tail Slap")] TailSlap = 640,
        [Display(Name = "Hysteric Barrage")] HystericBarrage = 641,
        [Display(Name = "Amplification")] Amplification = 642,
        [Display(Name = "Cannonball")] Cannonball = 643,
        [Display(Name = "Mind Blast")] MindBlast = 644,
        [Display(Name = "Exuviation")] Exuviation = 645,
        [Display(Name = "Magic Hammer")] MagicHammer = 646,
        [Display(Name = "Zephyr Mantle")] ZephyrMantle = 647,
        [Display(Name = "Regurgitation")] Regurgitation = 648,
        [Display(Name = "Seedspray")] Seedspray = 650,
        [Display(Name = "Corrosive Ooze")] CorrosiveOoze = 651,
        [Display(Name = "Spiral Spin")] SpiralSpin = 652,
        [Display(Name = "Asuran Claws")] AsuranClaws = 653,
        [Display(Name = "Sub-zero Smash")] SubZeroSmash = 654,
        [Display(Name = "Triumphant Roar")] TriumphantRoar = 655,
        [Display(Name = "Acrid Stream")] AcridStream = 656,
        [Display(Name = "Blazing Bound")] BlazingBound = 657,
        [Display(Name = "Plenilune Embrace")] PleniluneEmbrace = 658,
        [Display(Name = "Demoralizing Roar")] DemoralizingRoar = 659,
        [Display(Name = "Cimicine Discharge")] CimicineDischarge = 660,
        [Display(Name = "Animating Wail")] AnimatingWail = 661,
        [Display(Name = "Battery Charge")] BatteryCharge = 662,
        [Display(Name = "Leafstorm")] Leafstorm = 663,
        [Display(Name = "Regeneration")] Regeneration = 664,
        [Display(Name = "Final Sting")] FinalSting = 665,
        [Display(Name = "Goblin Rush")] GoblinRush = 666,
        [Display(Name = "Vanity Dive")] VanityDive = 667,
        [Display(Name = "Magic Barrier")] MagicBarrier = 668,
        [Display(Name = "Whirl of Rage")] WhirlOfRage = 669,
        [Display(Name = "Benthic Typhoon")] BenthicTyphoon = 670,
        [Display(Name = "Auroral Drape")] AuroralDrape = 671,
        [Display(Name = "Osmosis")] Osmosis = 672,
        [Display(Name = "Quad. Continuum")] QuadContinuum = 673,
        [Display(Name = "Fantod")] Fantod = 674,
        [Display(Name = "Thermal Pulse")] ThermalPulse = 675,
        [Display(Name = "Empty Thrash")] EmptyThrash = 677,
        [Display(Name = "Dream Flower")] DreamFlower = 678,
        [Display(Name = "Occultation")] Occultation = 679,
        [Display(Name = "Charged Whisker")] ChargedWhisker = 680,
        [Display(Name = "Winds of Promy.")] WindsOfPromy = 681,
        [Display(Name = "Delta Thrust")] DeltaThrust = 682,
        [Display(Name = "Evryone. Grudge")] EvryoneGrudge = 683,
        [Display(Name = "Reaving Wind")] ReavingWind = 684,
        [Display(Name = "Barrier Tusk")] BarrierTusk = 685,
        [Display(Name = "Mortal Ray")] MortalRay = 686,
        [Display(Name = "Water Bomb")] WaterBomb = 687,
        [Display(Name = "Heavy Strike")] HeavyStrike = 688,
        [Display(Name = "Dark Orb")] DarkOrb = 689,
        [Display(Name = "White Wind")] WhiteWind = 690,
        [Display(Name = "Sudden Lunge")] SuddenLunge = 692,
        [Display(Name = "Quadrastrike")] Quadrastrike = 693,
        [Display(Name = "Vapor Spray")] VaporSpray = 694,
        [Display(Name = "Thunder Breath")] ThunderBreath = 695,
        [Display(Name = "O. Counterstance")] OCounterstance = 696,
        [Display(Name = "Amorphic Spikes")] AmorphicSpikes = 697,
        [Display(Name = "Wind Breath")] WindBreath = 698,
        [Display(Name = "Barbed Crescent")] BarbedCrescent = 699,
        [Display(Name = "Nat. Meditation")] NatMeditation = 700,
        [Display(Name = "Tem. Upheaval")] TemUpheaval = 701,
        [Display(Name = "Rending Deluge")] RendingDeluge = 702,
        [Display(Name = "Embalming Earth")] EmbalmingEarth = 703,
        [Display(Name = "Paralyzing Triad")] ParalyzingTriad = 704,
        [Display(Name = "Foul Waters")] FoulWaters = 705,
        [Display(Name = "Glutinous Dart")] GlutinousDart = 706,
        [Display(Name = "Retinal Glare")] RetinalGlare = 707,
        [Display(Name = "Subduction")] Subduction = 708,
        [Display(Name = "Thrashing Assault")] ThrashingAssault = 709,
        [Display(Name = "Erratic Flutter")] ErraticFlutter = 710,
        [Display(Name = "Restoral")] Restoral = 711,
        [Display(Name = "Rail Cannon")] RailCannon = 712,
        [Display(Name = "Diffusion Ray")] DiffusionRay = 713,
        [Display(Name = "Sinker Drill")] SinkerDrill = 714,
        [Display(Name = "Molting Plumage")] MoltingPlumage = 715,
        [Display(Name = "Nectarous Deluge")] NectarousDeluge = 716,
        [Display(Name = "Sweeping Gouge")] SweepingGouge = 717,
        [Display(Name = "Atra. Libations")] AtraLibations = 718,
        [Display(Name = "Searing Tempest")] SearingTempest = 719,
        [Display(Name = "Spectral Floe")] SpectralFloe = 720,
        [Display(Name = "Anvil Lightning")] AnvilLightning = 721,
        [Display(Name = "Entomb")] Entomb = 722,
        [Display(Name = "Saurian Slide")] SaurianSlide = 723,
        [Display(Name = "Palling Salvo")] PallingSalvo = 724,
        [Display(Name = "Blinding Fulgor")] BlindingFulgor = 725,
        [Display(Name = "Scouring Spate")] ScouringSpate = 726,
        [Display(Name = "Silent Storm")] SilentStorm = 727,
        [Display(Name = "Tenebral Crush")] TenebralCrush = 728,
        [Display(Name = "Thunderbolt")] Thunderbolt = 736,
        [Display(Name = "Harden Shell")] HardenShell = 737,
        [Display(Name = "Absolute Terror")] AbsoluteTerror = 738,
        [Display(Name = "Gates of Hades")] GatesOfHades = 739,
        [Display(Name = "Tourbillion")] Tourbillion = 740,
        [Display(Name = "Pyric Bulwark")] PyricBulwark = 741,
        [Display(Name = "Bilgestorm")] Bilgestorm = 742,
        [Display(Name = "Bloodrake")] Bloodrake = 743,
        [Display(Name = "Droning Whirlwind")] DroningWhirlwind = 744,
        [Display(Name = "Carcharian Verve")] CarcharianVerve = 745,
        [Display(Name = "Blistering Roar")] BlisteringRoar = 746,
        [Display(Name = "Uproot")] Uproot = 747,
        [Display(Name = "Crashing Thunder")] CrashingThunder = 748,
        [Display(Name = "Polar Roar")] PolarRoar = 749,
        [Display(Name = "Mighty Guard")] MightyGuard = 750,
        [Display(Name = "Cruel Joke")] CruelJoke = 751,
        [Display(Name = "Cesspool")] Cesspool = 752,
        [Display(Name = "Tearing Gust")] TearingGust = 753,
        [Display(Name = "Indi-Regen")] IndiRegen = 768,
        [Display(Name = "Indi-Poison")] IndiPoison = 769,
        [Display(Name = "Indi-Refresh")] IndiRefresh = 770,
        [Display(Name = "Indi-Haste")] IndiHaste = 771,
        [Display(Name = "Indi-STR")] IndiSTR = 772,
        [Display(Name = "Indi-DEX")] IndiDEX = 773,
        [Display(Name = "Indi-VIT")] IndiVIT = 774,
        [Display(Name = "Indi-AGI")] IndiAGI = 775,
        [Display(Name = "Indi-INT")] IndiINT = 776,
        [Display(Name = "Indi-MND")] IndiMND = 777,
        [Display(Name = "Indi-CHR")] IndiCHR = 778,
        [Display(Name = "Indi-Fury")] IndiFury = 779,
        [Display(Name = "Indi-Barrier")] IndiBarrier = 780,
        [Display(Name = "Indi-Acumen")] IndiAcumen = 781,
        [Display(Name = "Indi-Fend")] IndiFend = 782,
        [Display(Name = "Indi-Precision")] IndiPrecision = 783,
        [Display(Name = "Indi-Voidance")] IndiVoidance = 784,
        [Display(Name = "Indi-Focus")] IndiFocus = 785,
        [Display(Name = "Indi-Attunement")] IndiAttunement = 786,
        [Display(Name = "Indi-Wilt")] IndiWilt = 787,
        [Display(Name = "Indi-Frailty")] IndiFrailty = 788,
        [Display(Name = "Indi-Fade")] IndiFade = 789,
        [Display(Name = "Indi-Malaise")] IndiMalaise = 790,
        [Display(Name = "Indi-Slip")] IndiSlip = 791,
        [Display(Name = "Indi-Torpor")] IndiTorpor = 792,
        [Display(Name = "Indi-Vex")] IndiVex = 793,
        [Display(Name = "Indi-Languor")] IndiLanguor = 794,
        [Display(Name = "Indi-Slow")] IndiSlow = 795,
        [Display(Name = "Indi-Paralysis")] IndiParalysis = 796,
        [Display(Name = "Indi-Gravity")] IndiGravity = 797,
        [Display(Name = "Geo-Regen")] GeoRegen = 798,
        [Display(Name = "Geo-Poison")] GeoPoison = 799,
        [Display(Name = "Geo-Refresh")] GeoRefresh = 800,
        [Display(Name = "Geo-Haste")] GeoHaste = 801,
        [Display(Name = "Geo-STR")] GeoSTR = 802,
        [Display(Name = "Geo-DEX")] GeoDEX = 803,
        [Display(Name = "Geo-VIT")] GeoVIT = 804,
        [Display(Name = "Geo-AGI")] GeoAGI = 805,
        [Display(Name = "Geo-INT")] GeoINT = 806,
        [Display(Name = "Geo-MND")] GeoMND = 807,
        [Display(Name = "Geo-CHR")] GeoCHR = 808,
        [Display(Name = "Geo-Fury")] GeoFury = 809,
        [Display(Name = "Geo-Barrier")] GeoBarrier = 810,
        [Display(Name = "Geo-Acumen")] GeoAcumen = 811,
        [Display(Name = "Geo-Fend")] GeoFend = 812,
        [Display(Name = "Geo-Precision")] GeoPrecision = 813,
        [Display(Name = "Geo-Voidance")] GeoVoidance = 814,
        [Display(Name = "Geo-Focus")] GeoFocus = 815,
        [Display(Name = "Geo-Attunement")] GeoAttunement = 816,
        [Display(Name = "Geo-Wilt")] GeoWilt = 817,
        [Display(Name = "Geo-Frailty")] GeoFrailty = 818,
        [Display(Name = "Geo-Fade")] GeoFade = 819,
        [Display(Name = "Geo-Malaise")] GeoMalaise = 820,
        [Display(Name = "Geo-Slip")] GeoSlip = 821,
        [Display(Name = "Geo-Torpor")] GeoTorpor = 822,
        [Display(Name = "Geo-Vex")] GeoVex = 823,
        [Display(Name = "Geo-Languor")] GeoLanguor = 824,
        [Display(Name = "Geo-Slow")] GeoSlow = 825,
        [Display(Name = "Geo-Paralysis")] GeoParalysis = 826,
        [Display(Name = "Geo-Gravity")] GeoGravity = 827,
        [Display(Name = "Fira")] Fira = 828,
        [Display(Name = "Fira II")] Fira2 = 829,
        [Display(Name = "Blizzara")] Blizzara = 830,
        [Display(Name = "Blizzara II")] Blizzara2 = 831,
        [Display(Name = "Aera")] Aera = 832,
        [Display(Name = "Aera II")] Aera2 = 833,
        [Display(Name = "Stonera")] Stonera = 834,
        [Display(Name = "Stonera II")] Stonera2 = 835,
        [Display(Name = "Thundara")] Thundara = 836,
        [Display(Name = "Thundara II")] Thundara2 = 837,
        [Display(Name = "Watera")] Watera = 838,
        [Display(Name = "Watera II")] Watera2 = 839,
        [Display(Name = "Foil")] Foil = 840,
        [Display(Name = "Distract")] Distract = 841,
        [Display(Name = "Distract II")] Distract2 = 842,
        [Display(Name = "Frazzle")] Frazzle = 843,
        [Display(Name = "Frazzle II")] Frazzle2 = 844,
        [Display(Name = "Flurry")] Flurry = 845,
        [Display(Name = "Flurry II")] Flurry2 = 846,
        [Display(Name = "Atomos")] Atomos = 847,
        [Display(Name = "Reraise IV")] Reraise4 = 848,
        [Display(Name = "Fire VI")] Fire6 = 849,
        [Display(Name = "Blizzard VI")] Blizzard6 = 850,
        [Display(Name = "Aero VI")] Aero6 = 851,
        [Display(Name = "Stone VI")] Stone6 = 852,
        [Display(Name = "Thunder VI")] Thunder6 = 853,
        [Display(Name = "Water VI")] Water6 = 854,
        [Display(Name = "Enlight II")] Enlight2 = 855,
        [Display(Name = "Endark II")] Endark2 = 856,
        [Display(Name = "Sandstorm II")] Sandstorm2 = 857,
        [Display(Name = "Rainstorm II")] Rainstorm2 = 858,
        [Display(Name = "Windstorm II")] Windstorm2 = 859,
        [Display(Name = "Firestorm II")] Firestorm2 = 860,
        [Display(Name = "Hailstorm II")] Hailstorm2 = 861,
        [Display(Name = "Thunderstorm II")] Thunderstorm2 = 862,
        [Display(Name = "Voidstorm II")] Voidstorm2 = 863,
        [Display(Name = "Aurorastorm II")] Aurorastorm2 = 864,
        [Display(Name = "Fira III")] Fira3 = 865,
        [Display(Name = "Blizzara III")] Blizzara3 = 866,
        [Display(Name = "Aera III")] Aera3 = 867,
        [Display(Name = "Stonera III")] Stonera3 = 868,
        [Display(Name = "Thundara III")] Thundara3 = 869,
        [Display(Name = "Watera III")] Watera3 = 870,
        [Display(Name = "Fire Threnody II")] FireThrenody2 = 871,
        [Display(Name = "Ice Threnody II")] IceThrenody2 = 872,
        [Display(Name = "Wind Threnody II")] WindThrenody2 = 873,
        [Display(Name = "Earth Threnody II")] EarthThrenody2 = 874,
        [Display(Name = "Ltng. Threnody II")] LtngThrenody2 = 875,
        [Display(Name = "Water Threnody II")] WaterThrenody2 = 876,
        [Display(Name = "Light Threnody II")] LightThrenody2 = 877,
        [Display(Name = "Dark Threnody II")] DarkThrenody2 = 878,
        [Display(Name = "Inundation")] Inundation = 879,
        [Display(Name = "Drain III")] Drain3 = 880,
        [Display(Name = "Aspir III")] Aspir3 = 881,
        [Display(Name = "Distract III")] Distract3 = 882,
        [Display(Name = "Frazzle III")] Frazzle3 = 883,
        [Display(Name = "Addle II")] Addle2 = 884,
        [Display(Name = "Geohelix II")] Geohelix2 = 885,
        [Display(Name = "Hydrohelix II")] Hydrohelix2 = 886,
        [Display(Name = "Anemohelix II")] Anemohelix2 = 887,
        [Display(Name = "Pyrohelix II")] Pyrohelix2 = 888,
        [Display(Name = "Cryohelix II")] Cryohelix2 = 889,
        [Display(Name = "Ionohelix II")] Ionohelix2 = 890,
        [Display(Name = "Noctohelix II")] Noctohelix2 = 891,
        [Display(Name = "Luminohelix II")] Luminohelix2 = 892,
        [Display(Name = "Full Cure")] FullCure = 893,
        [Display(Name = "Refresh III")] Refresh3 = 894,
        [Display(Name = "Temper II")] Temper2 = 895,
        [Display(Name = "Shantotto")] Shantotto = 896,
        [Display(Name = "Naji")] Naji = 897,
        [Display(Name = "Kupipi")] Kupipi = 898,
        [Display(Name = "Excenmille")] Excenmille = 899,
        [Display(Name = "Ayame")] Ayame = 900,
        [Display(Name = "Nanaa Mihgo")] NanaaMihgo = 901,
        [Display(Name = "Curilla")] Curilla = 902,
        [Display(Name = "Volker")] Volker = 903,
        [Display(Name = "Ajido-Marujido")] AjidoMarujido = 904,
        [Display(Name = "Trion")] Trion = 905,
        [Display(Name = "Zeid")] Zeid = 906,
        [Display(Name = "Lion")] Lion = 907,
        [Display(Name = "Tenzen")] Tenzen = 908,
        [Display(Name = "Mihli Aliapoh")] MihliAliapoh = 909,
        [Display(Name = "Valaineral")] Valaineral = 910,
        [Display(Name = "Joachim")] Joachim = 911,
        [Display(Name = "Naja Salaheem")] NajaSalaheem = 912,
        [Display(Name = "Prishe")] Prishe = 913,
        [Display(Name = "Ulmia")] Ulmia = 914,
        [Display(Name = "Shikaree Z")] ShikareeZ = 915,
        [Display(Name = "Cherukiki")] Cherukiki = 916,
        [Display(Name = "Iron Eater")] IronEater = 917,
        [Display(Name = "Gessho")] Gessho = 918,
        [Display(Name = "Gadalar")] Gadalar = 919,
        [Display(Name = "Rainemard")] Rainemard = 920,
        [Display(Name = "Ingrid")] Ingrid = 921,
        [Display(Name = "Lehko Habhoka")] LehkoHabhoka = 922,
        [Display(Name = "Nashmeira")] Nashmeira = 923,
        [Display(Name = "Zazarg")] Zazarg = 924,
        [Display(Name = "Ovjang")] Ovjang = 925,
        [Display(Name = "Mnejing")] Mnejing = 926,
        [Display(Name = "Sakura")] Sakura = 927,
        [Display(Name = "Luzaf")] Luzaf = 928,
        [Display(Name = "Najelith")] Najelith = 929,
        [Display(Name = "Aldo")] Aldo = 930,
        [Display(Name = "Moogle")] Moogle = 931,
        [Display(Name = "Fablinix")] Fablinix = 932,
        [Display(Name = "Maat")] Maat = 933,
        [Display(Name = "D. Shantotto")] DShantotto = 934,
        [Display(Name = "Star Sibyl")] StarSibyl = 935,
        [Display(Name = "Karaha-Baruha")] KarahaBaruha = 936,
        [Display(Name = "Cid")] Cid = 937,
        [Display(Name = "Gilgamesh")] Gilgamesh = 938,
        [Display(Name = "Areuhat")] Areuhat = 939,
        [Display(Name = "Semih Lafihna")] SemihLafihna = 940,
        [Display(Name = "Elivira")] Elivira = 941,
        [Display(Name = "Noillurie")] Noillurie = 942,
        [Display(Name = "Lhu Mhakaracca")] LhuMhakaracca = 943,
        [Display(Name = "Ferreous Coffin")] FerreousCoffin = 944,
        [Display(Name = "Lilisette")] Lilisette = 945,
        [Display(Name = "Mumor")] Mumor = 946,
        [Display(Name = "Uka Totlihn")] UkaTotlihn = 947,
        [Display(Name = "Klara")] Klara = 948,
        [Display(Name = "Romaa Mihgo")] RomaaMihgo = 949,
        [Display(Name = "Kuyin Hathdenna")] KuyinHathdenna = 950,
        [Display(Name = "Rahal")] Rahal = 951,
        [Display(Name = "Koru-Moru")] KoruMoru = 952,
        [Display(Name = "Pieuje (UC)")] PieujeUC = 953,
        [Display(Name = "I. Shield (UC)")] IShieldUC = 954,
        [Display(Name = "Apururu (UC)")] ApururuUC = 955,
        [Display(Name = "Jakoh (UC)")] JakohUC = 956,
        [Display(Name = "Flaviria (UC)")] FlaviriaUC = 957,
        [Display(Name = "Babban")] Babban = 958,
        [Display(Name = "Abenzio")] Abenzio = 959,
        [Display(Name = "Rughadjeen")] Rughadjeen = 960,
        [Display(Name = "Kukki-Chebukki")] KukkiChebukki = 961,
        [Display(Name = "Margret")] Margret = 962,
        [Display(Name = "Chacharoon")] Chacharoon = 963,
        [Display(Name = "Lhe Lhangavo")] LheLhangavo = 964,
        [Display(Name = "Arciela")] Arciela = 965,
        [Display(Name = "Mayakov")] Mayakov = 966,
        [Display(Name = "Qultada")] Qultada = 967,
        [Display(Name = "Adelheid")] Adelheid = 968,
        [Display(Name = "Amchuchu")] Amchuchu = 969,
        [Display(Name = "Brygid")] Brygid = 970,
        [Display(Name = "Mildaurion")] Mildaurion = 971,
        [Display(Name = "Halver")] Halver = 972,
        [Display(Name = "Rongelouts")] Rongelouts = 973,
        [Display(Name = "Leonoyne")] Leonoyne = 974,
        [Display(Name = "Maximilian")] Maximilian = 975,
        [Display(Name = "Kayeel-Payeel")] KayeelPayeel = 976,
        [Display(Name = "Robel-Akbel")] RobelAkbel = 977,
        [Display(Name = "Kupofried")] Kupofried = 978,
        [Display(Name = "Selh'teus")] SelhTeus = 979,
        [Display(Name = "Yoran-Oran (UC)")] YoranOranUC = 980,
        [Display(Name = "Sylvie (UC)")] SylvieUC = 981,
        [Display(Name = "Abquhbah")] Abquhbah = 982,
        [Display(Name = "Balamor")] Balamor = 983,
        [Display(Name = "August")] August = 984,
        [Display(Name = "Rosulatia")] Rosulatia = 985,
        [Display(Name = "Teodor")] Teodor = 986,
        [Display(Name = "Ullegore")] Ullegore = 987,
        [Display(Name = "Makki-Chebukki")] MakkiChebukki = 988,
        [Display(Name = "King of Hearts")] KingOfHearts = 989,
        [Display(Name = "Morimar")] Morimar = 990,
        [Display(Name = "Darrcuiln")] Darrcuiln = 991,
        [Display(Name = "AAHM")] AAHM = 992,
        [Display(Name = "AAEV")] AAEV = 993,
        [Display(Name = "AAMR")] AAMR = 994,
        [Display(Name = "AATT")] AATT = 995,
        [Display(Name = "AAGK")] AAGK = 996,
        [Display(Name = "Iroha")] Iroha = 997,
        [Display(Name = "Ygnas")] Ygnas = 998,
        [Display(Name = "Monberaux")] Monberaux = 999,
        [Display(Name = "Excenmille [S]")] ExcenmilleS = 1004,
        [Display(Name = "Ayame (UC)")] AyameUC = 1005,
        [Display(Name = "Maat (UC)")] MaatUC = 1006,
        [Display(Name = "Aldo (UC)")] AldoUC = 1007,
        [Display(Name = "Naja (UC)")] NajaUC = 1008,
        [Display(Name = "Lion II")] Lion2 = 1009,
        [Display(Name = "Zeid II")] Zeid2 = 1010,
        [Display(Name = "Prishe II")] Prishe2 = 1011,
        [Display(Name = "Nashmeira II")] Nashmeira2 = 1012,
        [Display(Name = "Lilisette II")] Lilisette2 = 1013,
        [Display(Name = "Tenzen II")] Tenzen2 = 1014,
        [Display(Name = "Mumor II")] Mumor2 = 1015,
        [Display(Name = "Ingrid II")] Ingrid2 = 1016,
        [Display(Name = "Arciela II")] Arciela2 = 1017,
        [Display(Name = "Iroha II")] Iroha2 = 1018,
        [Display(Name = "Shantotto II")] Shantotto2 = 1019,

    }
}
